In [ ]:
# 2021-09
# noodling around with GPT2's token embeddings
# has some handy utility functions at the bottom

In [2]:
import torch as t

In [3]:
from transformers import AutoTokenizer, AutoModelWithLMHead
  
tokenizer = AutoTokenizer.from_pretrained("gpt2")

model = AutoModelWithLMHead.from_pretrained("gpt2")

/home/adam/.local/lib/python3.6/site-packages/transformers/models/auto/modeling_auto.py:1010: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  FutureWarning,


In [4]:
from transformers import GPT2Model


In [5]:
w = list(model.transformer.wte.named_parameters())[0][1]

In [6]:
w.shape

torch.Size([50257, 768])

In [7]:
tok2tok = w @ w.T

In [ ]:
t.median(tok2tok)

In [9]:
tok2tok[41215]

tensor([3.2481, 2.6960, 4.7101,  ..., 8.3717, 8.0132, 3.1817],
       grad_fn=<SelectBackward>)

In [10]:
tok2tok[0].shape

torch.Size([50257])

In [11]:
outs = t.argmax(tok2tok, 0)

In [12]:
mismatch = t.where(outs != t.arange(50257))

In [35]:
_33[0].shape

torch.Size([172])

In [13]:
outs[mismatch]

tensor([41215, 41215, 41215, 41215, 41215, 41215, 41215, 41215, 41215, 41215,
        41215, 41215, 41215, 41215, 41215, 24847, 41215, 41215, 41215, 41215,
        41215, 41215, 41215, 41215, 41215, 41215, 41215, 41215, 41215, 41215,
        41215, 41215, 41215, 41215, 41215, 41215, 41215, 41215, 41215, 41215,
        41215, 41215, 41215, 24847, 41215, 21387, 27267, 32826, 30823, 48220,
        46248, 36591, 46503, 15948, 16480, 16549, 17402, 16010, 14581, 16504,
        48307, 49161, 48101, 17940, 25777, 25284, 27012, 25631, 23421, 21569,
        21607, 21816, 23604, 40029, 27079, 27429, 31135,  2941, 25705, 39379,
        28203, 15905, 37114, 25934, 19727, 33006, 18308, 41017, 29818, 31710,
        22614, 42747, 31359, 38036, 31274, 44023, 33387, 44814, 40610, 31632,
        34007, 36939, 41330, 49752, 39190, 38485, 42325, 41072, 43584, 40732,
        45001, 45696, 44059, 42184, 41191, 40404, 37338, 40540, 45355, 41243,
        47230, 42349, 29998, 42694, 45670, 49177, 49097,  5808, 

In [68]:
b'\xc3\x83\xc3\x82\xc3\x83\xc3\x82\xc3\x83\xc3\x82\xc3\x83\xc3\x82'.decode()

'ÃÂÃÂÃÂÃÂ'

In [71]:
b'\xf0'.decode()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: unexpected end of data

In [1]:
def tryuni(bs):
    try:
        return bs.decode()
    except UnicodeDecodeError:
        return bs

In [19]:
[(i, tryuni(ntoks2bbyts([i])), n.item(), ntoks2utxt([n.item()])) for i,n in zip(mismatch[0].numpy().tolist(),outs[mismatch])]

[(124, b'\xc0', 41215, 'conservancy'),
 (125, b'\xc1', 41215, 'conservancy'),
 (177, b'\xf5', 41215, 'conservancy'),
 (178, b'\xf6', 41215, 'conservancy'),
 (179, b'\xf7', 41215, 'conservancy'),
 (180, b'\xf8', 41215, 'conservancy'),
 (181, b'\xf9', 41215, 'conservancy'),
 (182, b'\xfa', 41215, 'conservancy'),
 (183, b'\xfb', 41215, 'conservancy'),
 (184, b'\xfc', 41215, 'conservancy'),
 (185, b'\xfd', 41215, 'conservancy'),
 (186, b'\xfe', 41215, 'conservancy'),
 (187, b'\xff', 41215, 'conservancy'),
 (188, '\x00', 41215, 'conservancy'),
 (189, '\x01', 41215, 'conservancy'),
 (190, '\x02', 24847, 'ModLoader'),
 (191, '\x03', 41215, 'conservancy'),
 (192, '\x04', 41215, 'conservancy'),
 (193, '\x05', 41215, 'conservancy'),
 (194, '\x06', 41215, 'conservancy'),
 (195, '\x07', 41215, 'conservancy'),
 (196, '\x08', 41215, 'conservancy'),
 (197, '\t', 41215, 'conservancy'),
 (199, '\x0b', 41215, 'conservancy'),
 (200, '\x0c', 41215, 'conservancy'),
 (201, '\r', 41215, 'conservancy'),
 (202

In [25]:
[print(f"{i}: {tryuni(ntoks2bbyts([i]))}")  for i in range(50257) if type(tryuni(ntoks2bbyts([i]))) == type('.') and '.' in tryuni(ntoks2bbyts([i]))]

13: .
492: ..
526: ."
737: ).
764:  .
986: ...
1106: ....
1539: .,
1911: ".
2014: .)
2109: ........
2637: .'
2644:  ...
3693: .[
4083: ].
4181: ................
4458: '.
6739:  ).
7225: %.
7874: .-
8183: .]
8864: ................................
9313: ..."
9816: .--
11074: ").
11207: .:
11485:  ..
11496: .'"
11580: ….
11757: /.
12179: .),
12195: .(
12359: .....
13402: .—
13531: .''
13557: ._
15089: .;
15729: .).
15885: .*
16317: ......
17405: \.
18161: ."[
18823: %).
19424:  ....
19570: .")
19571: ./
19588: !).
20004:  ........
20262:  (.
20740:  ].
21387: )."
22135:  ."
22345: ...]
22446: ().
23029: ...)
23193: ................................................................
24457:  ./
24620: *.
25295: )].
25780: .......
25970: .</
26214: "...
26513: )...
26894:  [...]
27071:  ".
27422: }.
27613: +.
27691: ').
27754: ........................
27896:  "...
27972:  ().
28401: >.
29225: ]."
29720: )).
29847: .<
29865: ?).
30827: '."
30864: …..
32203: .""
32535: .#
32756: .>>
33283: .",
34

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [33]:
tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens([23090, 23435, 23090]))

'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂearanceÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ'

In [76]:
sorted(list(ntok2vtok_d.values()), key=len)[-10:]

['------------------------------------------------',
 '--------------------------------------------------------',
 '----------------------------------------------------------------',
 'ÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤ',
 '................................................................',
 '================================================================',
 '________________________________________________________________',
 'Ġ----------------------------------------------------------------',
 'Ġ=================================================================',
 'ÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤ']

In [77]:
vtxt2utxt('ÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤÃĥÃĤ')

'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ'

In [50]:
ntok2vtok(41215)

'conservancy'

In [48]:
''.join([ntok2vtok_d[i] for i in range(256)])

'!"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿĀāĂ㥹ĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıIJijĴĵĶķĸĹĺĻļĽľĿŀŁłŃ'

In [18]:
import json

with open('gpt2-vocab.json') as json_file:
    vocab = json.load(json_file)

vtok2ntok_d = vocab
ntok2vtok_d = {v:k for k,v in vtok2ntok_d.items()}

bs = (
    list(range(ord("!"), ord("~") + 1)) + list(range(ord("¡"), ord("¬") + 1)) + list(range(ord("®"), ord("ÿ") + 1))
)
cs = bs[:]
n = 0
for b in range(2 ** 8):
    if b not in bs:
        bs.append(b)
        cs.append(2 ** 8 + n)
        n += 1
cs = [chr(n) for n in cs]
nbyt2vchr_d = dict(zip(bs, cs))
vchr2nbyt_d = dict(zip(cs, bs))

vtok2ntok = lambda x: vtok2ntok_d[x]
ntok2vtok = lambda x: ntok2vtok_d[x]
vchr2nbyt = lambda x: vchr2nbyt_d[x]
nbyt2vchr = lambda x: nbyt2vchr_d[x]

utxt2nbyts = lambda s: list(s.encode())
# nbyts2vchrs = lambda l: ''.join([nbyt2vchr(n) for n in l])
nbyts2vchrs = lambda l: ''.join(map(nbyt2vchr, l))
utxt2vtxt = lambda s: nbyts2vchrs(utxt2nbyts(s))
utok2ntok = lambda s: vtok2ntok(utxt2vtxt(s))

# vtxt2nbyts = lambda s: bytes([vchr2nbyt(c) for c in s])
vtxt2bbyts = lambda s: bytes(map(vchr2nbyt, s))
vtxt2nbyts = lambda s: list(map(vchr2nbyt, s))
vtxt2utxt = lambda s: vtxt2bbyts(s).decode()

ntoks2vtxt = lambda l: ''.join(map(ntok2vtok, l))

ntoks2utxt = lambda l: vtxt2utxt(ntoks2vtxt(l))
ntoks2bbyts = lambda l: vtxt2bbyts(ntoks2vtxt(l))

In [15]:
list(w.named_parameters())

[('weight',
  Parameter containing:
  tensor([[-0.1101, -0.0393,  0.0331,  ..., -0.1364,  0.0151,  0.0453],
          [ 0.0403, -0.0486,  0.0462,  ...,  0.0861,  0.0025,  0.0432],
          [-0.1275,  0.0479,  0.1841,  ...,  0.0899, -0.1297, -0.0879],
          ...,
          [-0.0445, -0.0548,  0.0123,  ...,  0.1044,  0.0978, -0.0695],
          [ 0.1860,  0.0167,  0.0461,  ..., -0.0963,  0.0785, -0.0225],
          [ 0.0514, -0.0277,  0.0499,  ...,  0.0070,  0.1552,  0.1207]],
         requires_grad=True))]